name: Markdown Lint and Broken Links Check

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
    paths:
      - '**.md'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install and run markdownlint
      run: |
        npm install -g markdownlint-cli
        markdownlint "**/*.md"

  broken-links-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install and run broken-link-checker
      run: |
        sudo apt-get install -y nodejs npm
        npm install -g broken-link-checker
        blc https://github.com/${{ github.repository }}/blob/${{ github.sha }}/README.md -ro --exclude '*.md' --get --filter-level 3 | tee broken_links.log || true

    - name: Move broken links to new markdown file
      run: |
        if [ -s broken_links.log ]; then
          echo "# Broken Links" > broken_links.md
          echo "" >> broken_links.md
          cat broken_links.log | grep 'BROKEN' | awk '{print $1}' | sort | uniq | sed 's/^/- /' >> broken_links.md
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add broken_links.md
          git commit -m "Move broken links to a new markdown file"
          git push
        fi
